### ISSUE TITLE
Text inside the search bar is not shown properly on mobile devices

### ISSUE THREAD

**Issue by gdjohn4s** [Exifly/ApiVault#184] opened 2023-05-28 23:58 UTC
## Describe the bug
The problem mainly concerns mobile devices.
When I enter something in the search bar, what I have typed gets hidden and cut off.

## To Reproduce
1. Type something in the search bar on a mobile device.

## Expected behavior
I should be able to correctly read what I have typed.

## Screenshots
![2023-05-26 19 28 10](https://github.com/Exifly/ApiVault/assets/19678157/49737b26-a03f-4a48-9e3e-ba27dbd1c66f)

## Smartphone (please complete the following information):
 - Browser [brave browser, safari]

**Comment by Taseeeer** [comment] 2023-05-29 07:59
@gdjohn4s you can assign this to me as well. I see what the issue is 😃

**Comment by gdjohn4s** [comment] 2023-05-29 13:16
ok, I'm going to assign this issue to you, thanks

**Closed** 2023-06-04 19:23 UTC
Labels: bug, good first issue, frontend
